//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDebtRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckDebtRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbonnentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AbonnentCode {
            get {
                return this.AbonnentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AbonnentCodeField, value) != true)) {
                    this.AbonnentCodeField = value;
                    this.RaisePropertyChanged("AbonnentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HashCode {
            get {
                return this.HashCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HashCodeField, value) != true)) {
                    this.HashCodeField = value;
                    this.RaisePropertyChanged("HashCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDebtResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckDebtResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebTest.ServiceReference1.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebTest.ServiceReference1.InitialParameters InitialParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIDField, value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebTest.ServiceReference1.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebTest.ServiceReference1.InitialParameters InitialParameters {
            get {
                return this.InitialParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialParametersField, value) != true)) {
                    this.InitialParametersField = value;
                    this.RaisePropertyChanged("InitialParameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitialParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InitialParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialsField;
        
        private double DebtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Debt {
            get {
                return this.DebtField;
            }
            set {
                if ((this.DebtField.Equals(value) != true)) {
                    this.DebtField = value;
                    this.RaisePropertyChanged("Debt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbonnentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AbonnentCode {
            get {
                return this.AbonnentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AbonnentCodeField, value) != true)) {
                    this.AbonnentCodeField = value;
                    this.RaisePropertyChanged("AbonnentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HashCode {
            get {
                return this.HashCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HashCodeField, value) != true)) {
                    this.HashCodeField = value;
                    this.RaisePropertyChanged("HashCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebTest.ServiceReference1.Error ErrorField;
        
        private int InternalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIDField, value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebTest.ServiceReference1.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int InternalID {
            get {
                return this.InternalIDField;
            }
            set {
                if ((this.InternalIDField.Equals(value) != true)) {
                    this.InternalIDField = value;
                    this.RaisePropertyChanged("InternalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PaymentServiceSoap")]
    public interface PaymentServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (CheckDebtResponses) of message CheckDebtResponses does not match the default value (CheckDebt)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDebtResponses", ReplyAction="*")]
        WebTest.ServiceReference1.CheckDebtResponses1 CheckDebt(WebTest.ServiceReference1.CheckDebtResponses request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDebtResponses", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.CheckDebtResponses1> CheckDebtAsync(WebTest.ServiceReference1.CheckDebtResponses request);
        
        // CODEGEN: Generating message contract since the wrapper name (luka) of message luka does not match the default value (Payment)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/luka", ReplyAction="*")]
        WebTest.ServiceReference1.luka1 Payment(WebTest.ServiceReference1.luka request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/luka", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.luka1> PaymentAsync(WebTest.ServiceReference1.luka request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckDebtResponses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckDebtResponses {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.CheckDebtRequest request;
        
        public CheckDebtResponses() {
        }
        
        public CheckDebtResponses(WebTest.ServiceReference1.CheckDebtRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckDebtResponsesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckDebtResponses1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.CheckDebtResponse CheckDebtResponsesResult;
        
        public CheckDebtResponses1() {
        }
        
        public CheckDebtResponses1(WebTest.ServiceReference1.CheckDebtResponse CheckDebtResponsesResult) {
            this.CheckDebtResponsesResult = CheckDebtResponsesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luka", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class luka {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.PaymentRequest request;
        
        public luka() {
        }
        
        public luka(WebTest.ServiceReference1.PaymentRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lukaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class luka1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.PaymentResponse lukaResult;
        
        public luka1() {
        }
        
        public luka1(WebTest.ServiceReference1.PaymentResponse lukaResult) {
            this.lukaResult = lukaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentServiceSoapChannel : WebTest.ServiceReference1.PaymentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceSoapClient : System.ServiceModel.ClientBase<WebTest.ServiceReference1.PaymentServiceSoap>, WebTest.ServiceReference1.PaymentServiceSoap {
        
        public PaymentServiceSoapClient() {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTest.ServiceReference1.CheckDebtResponses1 WebTest.ServiceReference1.PaymentServiceSoap.CheckDebt(WebTest.ServiceReference1.CheckDebtResponses request) {
            return base.Channel.CheckDebt(request);
        }
        
        public WebTest.ServiceReference1.CheckDebtResponse CheckDebt(WebTest.ServiceReference1.CheckDebtRequest request) {
            WebTest.ServiceReference1.CheckDebtResponses inValue = new WebTest.ServiceReference1.CheckDebtResponses();
            inValue.request = request;
            WebTest.ServiceReference1.CheckDebtResponses1 retVal = ((WebTest.ServiceReference1.PaymentServiceSoap)(this)).CheckDebt(inValue);
            return retVal.CheckDebtResponsesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.CheckDebtResponses1> WebTest.ServiceReference1.PaymentServiceSoap.CheckDebtAsync(WebTest.ServiceReference1.CheckDebtResponses request) {
            return base.Channel.CheckDebtAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTest.ServiceReference1.CheckDebtResponses1> CheckDebtAsync(WebTest.ServiceReference1.CheckDebtRequest request) {
            WebTest.ServiceReference1.CheckDebtResponses inValue = new WebTest.ServiceReference1.CheckDebtResponses();
            inValue.request = request;
            return ((WebTest.ServiceReference1.PaymentServiceSoap)(this)).CheckDebtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTest.ServiceReference1.luka1 WebTest.ServiceReference1.PaymentServiceSoap.Payment(WebTest.ServiceReference1.luka request) {
            return base.Channel.Payment(request);
        }
        
        public WebTest.ServiceReference1.PaymentResponse Payment(WebTest.ServiceReference1.PaymentRequest request) {
            WebTest.ServiceReference1.luka inValue = new WebTest.ServiceReference1.luka();
            inValue.request = request;
            WebTest.ServiceReference1.luka1 retVal = ((WebTest.ServiceReference1.PaymentServiceSoap)(this)).Payment(inValue);
            return retVal.lukaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.luka1> WebTest.ServiceReference1.PaymentServiceSoap.PaymentAsync(WebTest.ServiceReference1.luka request) {
            return base.Channel.PaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTest.ServiceReference1.luka1> PaymentAsync(WebTest.ServiceReference1.PaymentRequest request) {
            WebTest.ServiceReference1.luka inValue = new WebTest.ServiceReference1.luka();
            inValue.request = request;
            return ((WebTest.ServiceReference1.PaymentServiceSoap)(this)).PaymentAsync(inValue);
        }
    }
}
